# Change these first
owner: serversshnet # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Jagoanssh - Website
    check: "tcp-ping"
    url: jagoanssh.com
  - name: sg1.ipservers.xyz
    check: "tcp-ping"
    url: sg1.ipservers.xyz
  - name: sg2.ipservers.xyz
    check: "tcp-ping"
    url: sg2.ipservers.xyz
  - name: sg3.ipservers.xyz
    check: "tcp-ping"
    url: sg3.ipservers.xyz
  - name: sg4.ipservers.xyz
    check: "tcp-ping"
    url: sg4.ipservers.xyz
  - name: sg5.ipservers.xyz
    check: "tcp-ping"
    url: sg5.ipservers.xyz
  - name: sg6.ipservers.xyz
    check: "tcp-ping"
    url: sg6.ipservers.xyz
  - name: id.ipservers.xyz
    check: "tcp-ping"
    url: id.ipservers.xyz
  - name: id2.ipservers.xyz
    check: "tcp-ping"
    url: id2.ipservers.xyz
  - name: id3.ipservers.xyz
    check: "tcp-ping"
    url: id3.ipservers.xyz
  - name: us1.ipservers.xyz
    check: "tcp-ping"
    url: us1.ipservers.xyz
  - name: uk1.ipservers.xyz
    check: "tcp-ping"
    url: uk1.ipservers.xyz
  - name: fr.ipservers.xyz
    check: "tcp-ping"
    url: fr.ipservers.xyz
  - name: ge.ipservers.xyz
    check: "tcp-ping"
    url: ge.ipservers.xyz
  - name: sg1-7.ipservers.xyz
    check: "tcp-ping"
    url: sg1-7.ipservers.xyz
  - name: sg2-7.ipservers.xyz
    check: "tcp-ping"
    url: sg2-7.ipservers.xyz
  - name: sg3-7.ipservers.xyz
    check: "tcp-ping"
    url: sg3-7.ipservers.xyz
  - name: sg4-7.ipservers.xyz
    check: "tcp-ping"
    url: sg4-7.ipservers.xyz
  - name: us1-7.ipservers.xyz
    check: "tcp-ping"
    url: us1-7.ipservers.xyz
  - name: uk1-7.ipservers.xyz
    check: "tcp-ping"
    url: uk1-7.ipservers.xyz
  - name: id1-7.ipservers.xyz
    check: "tcp-ping"
    url: id1-7.ipservers.xyz
  - name: id2-7.ipservers.xyz
    check: "tcp-ping"
    url: id2-7.ipservers.xyz
  - name: id3-7.ipservers.xyz
    check: "tcp-ping"
    url: id3-7.ipservers.xyz
  - name: fr1-7.ipservers.xyz
    check: "tcp-ping"
    url: fr1-7.ipservers.xyz
  - name: ge1-7.ipservers.xyz
    check: "tcp-ping"
    url: ge1-7.ipservers.xyz
  - name: sg1-30.ipservers.xyz
    check: "tcp-ping"
    url: sg1-30.ipservers.xyz
  - name: sg2-30.ipservers.xyz
    check: "tcp-ping"
    url: sg2-30.ipservers.xyz
  - name: sg3-30.ipservers.xyz
    check: "tcp-ping"
    url: sg3-30.ipservers.xyz
  - name: sg4-30.ipservers.xyz
    check: "tcp-ping"
    url: sg4-30.ipservers.xyz
  - name: us1-30.ipservers.xyz
    check: "tcp-ping"
    url: us1-30.ipservers.xyz
  - name: uk1-30.ipservers.xyz
    check: "tcp-ping"
    url: uk1-30.ipservers.xyz
  - name: vip.ipservers.xyz
    check: "tcp-ping"
    url: vip.ipservers.xyz
  - name: vip2.ipservers.xyz
    check: "tcp-ping"
    url: vip2.ipservers.xyz
  - name: sg.vmes.xyz
    check: "tcp-ping"
    url: sg.vmes.xyz
    port: 443
  - name: sg2.vmes.xyz
    check: "tcp-ping"
    url: sg2.vmes.xyz
    port: 443
  - name: sg3.vmes.xyz
    check: "tcp-ping"
    url: sg3.vmes.xyz
    port: 443
  - name: sg4.vmes.xyz
    check: "tcp-ping"
    url: sg4.vmes.xyz
    port: 443
  - name: sg4.vmes.xyz
    check: "tcp-ping"
    url: sg4.vmes.xyz
    port: 443
  - name: sg5.vmes.xyz
    check: "tcp-ping"
    url: sg5.vmes.xyz
    port: 443
  - name: sg6.vmes.xyz
    check: "tcp-ping"
    url: sg6.vmes.xyz
    port: 443
  - name: sg7.vmes.xyz
    check: "tcp-ping"
    url: sg7.vmes.xyz
    port: 443
  - name: sg8.vmes.xyz
    check: "tcp-ping"
    url: sg8.vmes.xyz
    port: 443
  - name: us.vmes.xyz
    check: "tcp-ping"
    url: us.vmes.xyz
    port: 443
  - name: us2.vmes.xyz
    check: "tcp-ping"
    url: us2.vmes.xyz
    port: 443
  - name: sg1vless.ipservers.xyz
    check: "tcp-ping"
    url: sg1vless.ipservers.xyz
    port: 443
  - name: sg2vless.ipservers.xyz
    check: "tcp-ping"
    url: sg2vless.ipservers.xyz
    port: 443
  - name: sg3vless.ipservers.xyz
    check: "tcp-ping"
    url: sg3vless.ipservers.xyz
    port: 443
  - name: sg4vless.ipservers.xyz
    check: "tcp-ping"
    url: sg4vless.ipservers.xyz
    port: 443
  - name: sg5vless.ipservers.xyz
    check: "tcp-ping"
    url: sg5vless.ipservers.xyz
    port: 443
  - name: sgcvless.ipservers.xyz
    check: "tcp-ping"
    url: sgcvless.ipservers.xyz
    port: 443
  - name: sgtro.ipservers.xyz
    check: "tcp-ping"
    url: sgtro.ipservers.xyz
    port: 443
  - name: sg2tro.ipservers.xyz
    check: "tcp-ping"
    url: sg2tro.ipservers.xyz
    port: 443
  - name: sg3tro.ipservers.xyz
    check: "tcp-ping"
    url: sg3tro.ipservers.xyz
    port: 443
  - name: sg4tro.ipservers.xyz
    check: "tcp-ping"
    url: sg4tro.ipservers.xyz
    port: 443
  - name: ustro.ipservers.xyz
    check: "tcp-ping"
    url: ustro.ipservers.xyz
    port: 443
  - name: us2tro.ipservers.xyz
    check: "tcp-ping"
    url: us2tro.ipservers.xyz
    port: 443
  - name: sg1go.ipservers.xyz
    check: "tcp-ping"
    url: sg1go.ipservers.xyz
    port: 443
  - name: sg2go.ipservers.xyz
    check: "tcp-ping"
    url: sg2go.ipservers.xyz
    port: 443
  - name: sg3go.ipservers.xyz
    check: "tcp-ping"
    url: sg3go.ipservers.xyz
    port: 443
  - name: usgo.ipservers.xyz
    check: "tcp-ping"
    url: usgo.ipservers.xyz
    port: 443
  - name: sgcgo.ipservers.xyz
    check: "tcp-ping"
    url: sgcgo.ipservers.xyz
    port: 443
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.jagoanssh.com
  # baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Monitor server status for services on jagoanssh"
  introMessage: This is a server status page that uses real-time data  
  navbar:
    - title: Uptime
      href: /
    - title: Home
      href: https://tinyurl.com/jagoanssh
  theme: light
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
