# Change these first
owner: serversshnet # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Jagoanssh - Website
    check: "tcp-ping"
    url: jagoanssh.com
  - name: sg1.ipservers.xyz
    check: "tcp-ping"
    url: sg1.ipservers.xyz
  - name: sg2.ipservers.xyz
    check: "tcp-ping"
    url: sg2.ipservers.xyz
  - name: sg3.ipservers.xyz
    check: "tcp-ping"
    url: sg3.ipservers.xyz
  - name: sg4.ipservers.xyz
    check: "tcp-ping"
    url: sg4.ipservers.xyz
  - name: sg5.ipservers.xyz
    check: "tcp-ping"
    url: sg5.ipservers.xyz
  - name: sg6.ipservers.xyz
    check: "tcp-ping"
    url: sg6.ipservers.xyz
  - name: id.ipservers.xyz
    check: "tcp-ping"
    url: id.ipservers.xyz
  - name: id2.ipservers.xyz
    check: "tcp-ping"
    url: id2.ipservers.xyz
  - name: id3.ipservers.xyz
    check: "tcp-ping"
    url: id3.ipservers.xyz
  - name: us1.ipservers.xyz
    check: "tcp-ping"
    url: us1.ipservers.xyz
  - name: uk1.ipservers.xyz
    check: "tcp-ping"
    url: uk1.ipservers.xyz
  - name: fr.ipservers.xyz
    check: "tcp-ping"
    url: fr.ipservers.xyz
  - name: ge.ipservers.xyz
    check: "tcp-ping"
    url: ge.ipservers.xyz
  - name: sg1-7.ipservers.xyz
    check: "tcp-ping"
    url: sg1-7.ipservers.xyz
  - name: sg2-7.ipservers.xyz
    check: "tcp-ping"
    url: sg2-7.ipservers.xyz
  - name: sg3-7.ipservers.xyz
    check: "tcp-ping"
    url: sg3-7.ipservers.xyz
  - name: sg4-7.ipservers.xyz
    check: "tcp-ping"
    url: sg4-7.ipservers.xyz
  - name: us1-7.ipservers.xyz
    check: "tcp-ping"
    url: us1-7.ipservers.xyz
  - name: uk1-7.ipservers.xyz
    check: "tcp-ping"
    url: uk1-7.ipservers.xyz
  - name: id1-7.ipservers.xyz
    check: "tcp-ping"
    url: id1-7.ipservers.xyz
  - name: id2-7.ipservers.xyz
    check: "tcp-ping"
    url: id2-7.ipservers.xyz
  - name: id3-7.ipservers.xyz
    check: "tcp-ping"
    url: id3-7.ipservers.xyz
  - name: fr1-7.ipservers.xyz
    check: "tcp-ping"
    url: fr1-7.ipservers.xyz
  - name: ge1-7.ipservers.xyz
    check: "tcp-ping"
    url: ge1-7.ipservers.xyz
  - name: sg1-30.ipservers.xyz
    check: "tcp-ping"
    url: sg1-30.ipservers.xyz
  - name: sg2-30.ipservers.xyz
    check: "tcp-ping"
    url: sg2-30.ipservers.xyz
  - name: sg3-30.ipservers.xyz
    check: "tcp-ping"
    url: sg3-30.ipservers.xyz
  - name: sg4-30.ipservers.xyz
    check: "tcp-ping"
    url: sg4-30.ipservers.xyz
  - name: us1-30.ipservers.xyz
    check: "tcp-ping"
    url: us1-30.ipservers.xyz
  - name: uk1-30.ipservers.xyz
    check: "tcp-ping"
    url: uk1-30.ipservers.xyz
  - name: vip.ipservers.xyz
    check: "tcp-ping"
    url: vip.ipservers.xyz
  - name: vip2.ipservers.xyz
    check: "tcp-ping"
    url: vip2.ipservers.xyz
  - name: idtr.jagoan.vip
    check: "tcp-ping"
    url: idtr.jagoan.vip
    port: 443
  - name: id2tr.jagoan.vip
    check: "tcp-ping"
    url: idtr.jagoan.vip
    port: 443
  - name: idray.jagoan.vip
    check: "tcp-ping"
    url: idray.jagoan.vip
    port: 443
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.jagoanssh.com
  # baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Uptime
      href: /
    - title: Home
      href: https://tinyurl.com/jagoanssh
  theme: ocean
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
#  graphs: "*/5 * * * *"
#  responseTime: "*/5 * * * *"
#  staticSite: "*/5 * * * *"
#  summary: "*/5 * * * *"
#  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
